name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        enable-stack: true

    - name: Build
      run: stack install --local-bin-path ./
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Pie for ${{ runner.os }}
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ./Pie
          ./Pie.exe
